# Generated by Django 3.2.4 on 2021-07-30 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('url_link', models.URLField()),
                ('published_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
