# Generated by Django 3.2.4 on 2021-07-31 11:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('video', '0001_initial'),
        ('playlist', '0002_alter_playlist_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='add_video_to_playlist',
            name='video',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='video.video', unique=True),
        ),
    ]
